/*
March 22, 2017
Prompts user for their name and birthday, then displays both in sentence form
Brett Castellano
 */

/**
 *
 * @author brcas1396
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purplePanel = new javax.swing.JPanel();
        happyBirthday = new javax.swing.JLabel();
        enterName = new javax.swing.JLabel();
        enterBirthday = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        birthdayField = new javax.swing.JTextField();
        finalSentence = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        birthdayGif = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuBar_File = new javax.swing.JMenu();
        file_Quit = new javax.swing.JMenuItem();
        menuBar_Edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        purplePanel.setBackground(new java.awt.Color(102, 0, 255));

        happyBirthday.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        happyBirthday.setText("Happy Birthday!");

        enterName.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        enterName.setText("Enter Your Name:");

        enterBirthday.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        enterBirthday.setText("Enter Your Birthday:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        birthdayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayFieldActionPerformed(evt);
            }
        });

        finalSentence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        birthdayGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/100.gif"))); // NOI18N

        javax.swing.GroupLayout purplePanelLayout = new javax.swing.GroupLayout(purplePanel);
        purplePanel.setLayout(purplePanelLayout);
        purplePanelLayout.setHorizontalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purplePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(happyBirthday)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purplePanelLayout.createSequentialGroup()
                .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(purplePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(finalSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(purplePanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(purplePanelLayout.createSequentialGroup()
                                .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enterButton)
                                    .addComponent(enterBirthday))
                                .addGap(35, 35, 35)))
                        .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(purplePanelLayout.createSequentialGroup()
                                .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(birthdayField))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(purplePanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(birthdayGif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        purplePanelLayout.setVerticalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purplePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(happyBirthday)
                .addGap(37, 37, 37)
                .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterName)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBirthday)
                    .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purplePanelLayout.createSequentialGroup()
                        .addComponent(birthdayGif, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(purplePanelLayout.createSequentialGroup()
                        .addComponent(enterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(finalSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        menuBar_File.setText("File");

        file_Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        file_Quit.setText("Quit");
        file_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_QuitActionPerformed(evt);
            }
        });
        menuBar_File.add(file_Quit);

        menuBar.add(menuBar_File);

        menuBar_Edit.setText("Edit");
        menuBar.add(menuBar_Edit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purplePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purplePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        String name = "";   //declare variable, for name which will be inputed
        String birthday = "";   //declare variable, for birthday which will be inputed
        name = nameField.getText(); //assigns typed name to variable "name"
        birthday = birthdayField.getText(); //assigns typed birthday to variable "birthday"
        finalSentence.setText(name + "'s birthday is " + birthday); //displays typed name and birtdhay in sentence form
    }//GEN-LAST:event_enterButtonActionPerformed

    private void birthdayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFieldActionPerformed

    private void file_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_QuitActionPerformed
        System.exit(0); //closes application
    }//GEN-LAST:event_file_QuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdayField;
    private javax.swing.JLabel birthdayGif;
    private javax.swing.JLabel enterBirthday;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel enterName;
    private javax.swing.JMenuItem file_Quit;
    private javax.swing.JLabel finalSentence;
    private javax.swing.JLabel happyBirthday;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBar_Edit;
    private javax.swing.JMenu menuBar_File;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel purplePanel;
    // End of variables declaration//GEN-END:variables
}
